### ISSUE TITLE
Installing module results in a WSOD

### ISSUE THREAD

**Issue by mjordan** [guilmour-asc/rest_oai#1]
Apache's error.log says

> Error: Class 'Drupal\\rest_oai\\Encoder\\OaiXmlEncoder' not found in /var/www/html/drupal/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 258

Changing the name of the class file to `OaiXmlEncoder.php` fixes the problem. PR forthcoming.

**Comment by guilmour-asc** [comment]
Closing the issue, as it seems that the problem has been fixed.
And also, congratulations to @mjordan for fixing. 💐️
